from rest_framework.routers import DefaultRouter
from django.urls import path, include
from .views import ProjectViewSet, TaskViewSet

# Create a router instance
router = DefaultRouter()

# Register the ViewSets with the router
# This generates URLs like:
# /projects/
# /projects/{pk}/
# /projects/{pk}/tasks/
router.register(r'projects', ProjectViewSet, basename='project')

# This generates URLs like:
# /tasks/
# /tasks/{pk}/
router.register(r'tasks', TaskViewSet, basename='task')

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]