# Generated by Django 5.2.7 on 2025-10-30 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this project belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['status', 'end_date'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('contract', 'Contract'), ('proposal', 'Proposal'), ('report', 'Report'), ('agreement', 'Agreement'), ('specification', 'Specification'), ('meeting_minutes', 'Meeting Minutes'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('final', 'Final')], default='draft', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Main content of the document')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(blank=True, help_text='Uploaded file version of the document', null=True, upload_to='documents/%Y/%m/%d/')),
                ('requires_signatures', models.BooleanField(default=False)),
                ('signature_required_count', models.PositiveIntegerField(default=0, help_text='Number of signatures required for this document')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this document belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.organization')),
                ('project', models.ForeignKey(blank=True, help_text='Optional project this document is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
                ('task', models.ForeignKey(blank=True, help_text='Optional task this document is associated with.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.task')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'title', 'version')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template_type', models.CharField(choices=[('contract', 'Contract'), ('proposal', 'Proposal'), ('report', 'Report'), ('agreement', 'Agreement'), ('form', 'Form')], default='contract', max_length=20)),
                ('content', models.TextField(help_text='Template content with variables')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_templates', to='core.organization')),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_type', models.CharField(choices=[('digital', 'Digital Signature'), ('handwritten', 'Handwritten Signature'), ('electronic', 'Electronic Consent'), ('clickwrap', 'Clickwrap Agreement')], default='electronic', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('is_signed', models.BooleanField(default=False)),
                ('signature_data', models.TextField(blank=True, help_text='Actual signature data (encrypted signature, image path, etc.)')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where the document was signed', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent of the browser used for signing')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Signature request expiration date', null=True)),
                ('decline_reason', models.TextField(blank=True, help_text='Reason for declining to sign')),
                ('signature_order', models.PositiveIntegerField(default=0, help_text='Order in which signatures should be collected')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='projects.document')),
                ('signatory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['signature_order', 'sent_at'],
                'unique_together': {('document', 'signatory')},
            },
        ),
    ]
