# Generated by Django 5.2.7 on 2025-10-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('ceo', 'CEO'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('accountant', 'Accountant'), ('hr', 'HR'), ('administrator', 'Administrator'), ('staff', 'Staff'), ('contributor', 'Contributor'), ('individual', 'Individual')], default='contributor', help_text='Role the user will have upon acceptance', max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('ceo', 'CEO'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('accountant', 'Accountant'), ('hr', 'HR'), ('administrator', 'Administrator'), ('staff', 'Staff'), ('contributor', 'Contributor'), ('individual', 'Individual')], default='staff', help_text="User's role within the organization", max_length=50),
        ),
    ]
