# Generated by Django 5.2.7 on 2025-10-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invitation_role_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invitation',
            unique_together={('email', 'organization')},
        ),
    ]
