# Generated by Django 5.2.7 on 2025-10-19 13:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='organizationmembership',
            options={'ordering': ['-created_at'], 'verbose_name': 'Organization Membership', 'verbose_name_plural': 'Organization Memberships'},
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Primary organization for this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_members', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationmembership_set', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('ceo', 'CEO'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('accountant', 'Accountant'), ('hr', 'HR'), ('administrator', 'Administrator'), ('staff', 'Staff'), ('contributor', 'Contributor')], default='staff', help_text="User's role within the organization", max_length=50),
        ),
        migrations.AlterField(
            model_name='organizationmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizationmembership_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email address of the person being invited', max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('ceo', 'CEO'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('accountant', 'Accountant'), ('hr', 'HR'), ('administrator', 'Administrator'), ('staff', 'Staff'), ('contributor', 'Contributor')], default='contributor', help_text='Role the user will have upon acceptance', max_length=50)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiration date for the invitation', null=True)),
                ('message', models.TextField(blank=True, help_text='Optional personal message to include with the invitation', null=True)),
                ('invited_by', models.ForeignKey(help_text='User who sent this invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.organization')),
            ],
            options={
                'verbose_name': 'Invitation',
                'verbose_name_plural': 'Invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='core_invita_token_5980a2_idx'), models.Index(fields=['email', 'is_accepted'], name='core_invita_email_f1da5c_idx')],
                'unique_together': {('email', 'organization', 'is_accepted')},
            },
        ),
    ]
