# Generated by Django 5.2.7 on 2025-10-19 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_alter_customuser_managers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_template', models.TextField(help_text='HTML/Markdown content with placeholders (e.g., {{user.first_name}}).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='The organization this template belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.organization')),
            ],
            options={
                'verbose_name': 'Document Template',
                'unique_together': {('organization', 'title')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('signed', 'Signed/Final'), ('rejected', 'Rejected')], default='draft', max_length=50)),
                ('final_content', models.TextField(blank=True, help_text='The rendered HTML content of the document instance.', null=True)),
                ('file_attachment', models.FileField(blank=True, help_text='The final PDF or file representation.', null=True, upload_to='documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_documents', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documenttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignatureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('signer_role', models.CharField(max_length=50)),
                ('content_hash', models.CharField(blank=True, help_text="SHA256 hash of the document's content at the time of signing.", max_length=64, null=True)),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='documents.document')),
            ],
            options={
                'verbose_name': 'Digital Signature Log',
                'unique_together': {('document', 'signer')},
            },
        ),
        migrations.CreateModel(
            name='DocumentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('ceo', 'CEO'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('accountant', 'Accountant'), ('hr', 'HR'), ('administrator', 'Administrator'), ('staff', 'Staff')], max_length=50, null=True)),
                ('permission_type', models.CharField(choices=[('view', 'Can View'), ('edit', 'Can Edit'), ('sign', 'Can Sign')], max_length=10)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='documents.document')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('document', 'user', 'permission_type')},
            },
        ),
    ]
