# Generated by Django 5.2.7 on 2025-10-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpermission',
            name='role',
            field=models.CharField(blank=True, choices=[('owner', 'Owner'), ('ceo', 'CEO'), ('manager', 'Manager'), ('assistant_manager', 'Assistant Manager'), ('accountant', 'Accountant'), ('hr', 'HR'), ('administrator', 'Administrator'), ('staff', 'Staff'), ('contributor', 'Contributor'), ('individual', 'Individual')], max_length=50, null=True),
        ),
    ]
