# Generated by Django 5.2.7 on 2025-10-24 11:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_invitation_role_and_more'),
        ('documents', '0002_alter_documentpermission_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('is_internal', models.BooleanField(default=False, help_text='Internal comment (not visible to external parties)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Comment',
                'verbose_name_plural': 'Document Comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(help_text='Unique token for external sharing', max_length=64, unique=True)),
                ('shared_with_email', models.EmailField(blank=True, help_text='Email of person document is shared with', max_length=254)),
                ('permission_type', models.CharField(choices=[('view', 'Can View'), ('comment', 'Can Comment'), ('edit', 'Can Edit'), ('sign', 'Can Sign')], default='view', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('access_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Document Share',
                'verbose_name_plural': 'Document Shares',
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('content', models.TextField()),
                ('changes', models.TextField(blank=True, help_text='Description of changes in this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Version',
                'verbose_name_plural': 'Document Versions',
                'ordering': ['document', '-version_number'],
            },
        ),
        migrations.AlterModelOptions(
            name='digitalsignaturelog',
            options={'ordering': ['-signed_at'], 'verbose_name': 'Digital Signature Log', 'verbose_name_plural': 'Digital Signature Logs'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documents'},
        ),
        migrations.AlterModelOptions(
            name='documentpermission',
            options={'verbose_name': 'Document Permission', 'verbose_name_plural': 'Document Permissions'},
        ),
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['name'], 'verbose_name': 'Document Template'},
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='digitalsignaturelog',
            name='invalidated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='digitalsignaturelog',
            name='invalidated_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='digitalsignaturelog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of signer', null=True),
        ),
        migrations.AddField(
            model_name='digitalsignaturelog',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='digitalsignaturelog',
            name='signature_data',
            field=models.TextField(blank=True, help_text='Encrypted signature data or hash'),
        ),
        migrations.AddField(
            model_name='digitalsignaturelog',
            name='signing_reason',
            field=models.CharField(blank=True, help_text='Reason for signing', max_length=255),
        ),
        migrations.AddField(
            model_name='digitalsignaturelog',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser/user agent information'),
        ),
        migrations.AddField(
            model_name='document',
            name='file_description',
            field=models.CharField(blank=True, help_text='Description of the attached file', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='granted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='granted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='granted_document_permissions', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='content',
            field=models.TextField(default='', help_text='HTML/Markdown content with placeholders (e.g., {{user.first_name}}).'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Template description and usage notes'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(default='', help_text="Template name (e.g., 'Employment Contract')", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='digitalsignaturelog',
            name='signer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_signatures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='document',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.organization'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('pending_approval', 'Pending Approval'), ('pending_final_signature', 'Pending Final Signature'), ('signed', 'Signed/Final'), ('archived', 'Archived'), ('rejected', 'Rejected')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='document',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.documenttemplate'),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='permission_type',
            field=models.CharField(choices=[('view', 'Can View'), ('comment', 'Can Comment'), ('edit', 'Can Edit'), ('sign', 'Can Sign')], max_length=10),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='content_template',
            field=models.TextField(blank=True, help_text="Legacy field - use 'content' instead."),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='title',
            field=models.CharField(blank=True, help_text='Display title (optional)', max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='documenttemplate',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'status'], name='documents_d_organiz_b8cccc_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'created_by'], name='documents_d_organiz_512e3c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['organization', 'template'], name='documents_d_organiz_c170c0_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents_document_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents.document'),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_document_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='documents.document'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['share_token'], name='documents_d_share_t_57bd35_idx'),
        ),
        migrations.AddIndex(
            model_name='documentshare',
            index=models.Index(fields=['expires_at'], name='documents_d_expires_4b27d0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
    ]
