# Generated by Django 5.2.7 on 2025-10-30 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '__first__'),
        ('core', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., 'High-Value Expense Approval'", max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to='core.organization')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
            },
        ),
        migrations.CreateModel(
            name='DocumentApprovalFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('is_complete', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_step_started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('current_deadline', models.DateTimeField(blank=True, null=True)),
                ('auto_escalate_after', models.DateTimeField(blank=True, null=True)),
                ('current_approver', models.ForeignKey(blank=True, help_text='The specific user assigned to approve this step.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flow', to='documents.document')),
                ('workflow_template', models.ForeignKey(help_text='The template this flow is based on.', on_delete=django.db.models.deletion.PROTECT, to='workflow.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Document Approval Flow Instance',
                'verbose_name_plural': 'Document Approval Flow Instances',
            },
        ),
        migrations.CreateModel(
            name='ApprovalChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('approval_flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room_link', to='workflow.documentapprovalflow')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approver_role', models.CharField(choices=[('viewer', 'Viewer'), ('contributor', 'Contributor'), ('manager', 'Manager'), ('admin', 'Administrator'), ('owner', 'Owner'), ('staff', 'Staff')], help_text='The role required for approval at this step.', max_length=50)),
                ('step_order', models.IntegerField(help_text='The sequence number (1, 2, 3...)')),
                ('next_step_routes', models.JSONField(blank=True, default=dict, help_text='JSON mapping of decision keys to subsequent step_order numbers. Use 0 to end workflow.')),
                ('timeout_days', models.PositiveIntegerField(default=7, help_text='Number of days before this step is considered overdue')),
                ('require_all_approvers', models.BooleanField(default=False, help_text='If True, all users with this role must approve. If False, any one can approve.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_steps', to='workflow.approvalworkflow')),
            ],
            options={
                'verbose_name': 'Workflow Template Step',
                'verbose_name_plural': 'Workflow Template Steps',
                'ordering': ['step_order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowMessageContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow_action', models.CharField(blank=True, max_length=50)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.message')),
                ('related_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowtemplatestep')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('approve', 'Approved/Pushed Up'), ('reject', 'Rejected'), ('route', 'Decision Route Taken'), ('forward', 'Forwarded to New Approver'), ('escalate', 'Escalated'), ('delegate', 'Delegated')], max_length=50)),
                ('decision_key', models.CharField(blank=True, help_text='The specific decision route taken', max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='The user who took the action.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_logs', to='documents.document')),
                ('from_step', models.ForeignKey(blank=True, help_text='The step this action was taken from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowtemplatestep')),
                ('template_step', models.ForeignKey(blank=True, help_text='The step definition this action relates to.', null=True, on_delete=django.db.models.deletion.PROTECT, to='workflow.workflowtemplatestep')),
                ('to_step', models.ForeignKey(blank=True, help_text='The step this action moved to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='workflow.workflowtemplatestep')),
            ],
            options={
                'verbose_name': 'Workflow Log',
                'verbose_name_plural': 'Workflow Logs',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='documentapprovalflow',
            name='current_template_step',
            field=models.ForeignKey(blank=True, help_text='The definition of the step currently awaiting action.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.workflowtemplatestep'),
        ),
        migrations.AddIndex(
            model_name='approvalworkflow',
            index=models.Index(fields=['organization', 'is_active'], name='workflow_ap_organiz_fc00bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='approvalworkflow',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='approvalchatroom',
            index=models.Index(fields=['approval_flow'], name='workflow_ap_approva_0f894d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtemplatestep',
            index=models.Index(fields=['workflow', 'step_order'], name='workflow_wo_workflo_158f69_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workflowtemplatestep',
            unique_together={('workflow', 'step_order')},
        ),
        migrations.AddIndex(
            model_name='workflowmessagecontext',
            index=models.Index(fields=['message'], name='workflow_wo_message_66e01c_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowmessagecontext',
            index=models.Index(fields=['related_step'], name='workflow_wo_related_2dda7a_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowlog',
            index=models.Index(fields=['document', 'created_at'], name='workflow_wo_documen_a6528e_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowlog',
            index=models.Index(fields=['actor', 'created_at'], name='workflow_wo_actor_i_8e9b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapprovalflow',
            index=models.Index(fields=['document', 'is_complete'], name='workflow_do_documen_40a28f_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapprovalflow',
            index=models.Index(fields=['current_approver', 'is_complete'], name='workflow_do_current_d4e1e4_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapprovalflow',
            index=models.Index(fields=['status', 'current_deadline'], name='workflow_do_status_445af6_idx'),
        ),
    ]
