# Generated by Django 5.2.7 on 2025-10-22 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(help_text='The sequence number for this step (e.g., 1, 2, 3).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', help_text='Current status of the approval step.', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Comments or feedback from the approver.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_steps', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(help_text='The document this step belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='documents.document')),
            ],
            options={
                'verbose_name_plural': 'Approval Steps',
                'ordering': ['document', 'order'],
                'unique_together': {('document', 'order')},
            },
        ),
    ]
